---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present

- name: Create directory for GPG keys
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Download Jenkins repository key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    filename: jenkins
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present