---
- name: Include Docker setup tasks
  include_tasks: docker.yml

- name: Include containerd configuration tasks
  include_tasks: containerd.yml

- name: Include system configuration tasks
  include_tasks: system.yml

- name: Include Kubernetes installation tasks
  include_tasks: k8s.yml