---
- name: Disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '# \1'

- name: Disable active swap
  command: swapoff -a

- name: Install SELinux utilities
  apt:
    name: selinux-utils
    state: present



- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Make IP forwarding persistent
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward = 1'
    state: present

- name: Set hostname
  hostname:
    name: "{{ node_hostname }}"