---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required system packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Retrieve system architecture using dpkg
  command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Add Docker repository to Apt sources
  apt_repository:
    repo: "deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    update_cache: yes

- name: Install Docker and related packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add specified users to the docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
