- name: this is for master kubernetes
  hosts: master
  gather_facts: true
  become: true
  vars:
    node_hostname: "master"
    kubeadm_init_apiserver_advertise_address: "{{ ansible_default_ipv4.address }}"
    kubeadm_init_control_plane_endpoint: "{{ hostvars[inventory_hostname]['public_ip'] }}"
    kube_join_role: master

  roles:
    - k8s-node-setup
    - kubeadm
    - cni

- name: this is for workers kubernetes
  hosts: workers
  gather_facts: true
  become: true
  vars:
    node_hostname: "worker{{ ansible_play_hosts.index(inventory_hostname) + 1 }}"
    kube_join_role: worker
  roles:
    - k8s-node-setup
    - join

- name: this is for jenkins
  hosts: jenkins
  gather_facts: true
  become: true

  roles:
    - jenkins
    - docker
    
- name: this is for jenkins slave
  hosts: jenkins-slave
  gather_facts: true
  become: true

  roles:
    - java
    - docker

- name: this is for sonarqube
  hosts: sonarqube
  gather_facts: true
  become: true

  roles:
    - roles/sonar
